// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riqjidlyjyhfpgnjtbqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpcWppZGx5anloZnBnbmp0YnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMTQ5MTMsImV4cCI6MjA4NTU5MDkxM30.V6Xz1v_fqe_Ebk_-1ybx2tSIfLVXfw-v29GuXnyMdug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});